site_name: ols-py
repo_url: https://github.com/ahida-development/ols-py
extra_css:
  - css/extra.css

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Introduction: 'index.md'
  - Client: 'client.md'
  - Request/Response Schemas: 'schemas.md'
  - changelog.md

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true

plugins:
  - search:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            paths: [src]
            docstring_style: sphinx
            show_root_heading: true
            merge_init_into_class: true
            docstring_section_style: list
            show_signature_annotations: true
            show_source: false
